-- ==============================================================================
-- The Philippine Artisan (TPA) - Database Audit Logging & Activity Tracking Setup
-- ==============================================================================
-- Run this script in your Supabase Dashboard -> SQL Editor to enable automatic
-- audit logging on your admin tables.
-- ==============================================================================

-- 1. Create the audit_logs table
create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    action text not null, -- 'INSERT', 'UPDATE', 'DELETE'
    record_id text,
    user_id uuid,
    user_email text,
    old_data jsonb,
    new_data jsonb,
    created_at timestamp with time zone default now()
);

-- Index for fast queries ordered by created_at
create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);
create index if not exists idx_audit_logs_table_name on public.audit_logs (table_name);
create index if not exists idx_audit_logs_action on public.audit_logs (action);

-- 2. Enable Row Level Security (RLS) on audit_logs
alter table public.audit_logs enable row level security;

-- Policy: Authenticated users (logged-in admins) can read the audit logs
drop policy if exists "Authenticated users can read audit logs" on public.audit_logs;
create policy "Authenticated users can read audit logs"
on public.audit_logs
for select
to authenticated
using (true);

-- Policy: Prevent manual tampering or deletes via API
drop policy if exists "No one can update audit logs" on public.audit_logs;
create policy "No one can update audit logs"
on public.audit_logs
for update
using (false);

drop policy if exists "No one can delete audit logs" on public.audit_logs;
create policy "No one can delete audit logs"
on public.audit_logs
for delete
using (false);


-- 3. Create the Trigger Function
create or replace function public.process_audit_log()
returns trigger
language plpgsql
security definer
as $$
declare
    current_user_id uuid;
    current_user_email text;
    rec_id text;
begin
    -- Extract the authenticated user id and email from Supabase auth JWT
    current_user_id := auth.uid();
    current_user_email := auth.jwt() ->> 'email';

    -- Extract record identifier across different tables
    if (tg_op = 'DELETE') then
        rec_id := coalesce(
            old.article_id::text,
            old.staff_id::text,
            old.pubmat_id::text,
            old.id::text,
            null
        );
        insert into public.audit_logs (table_name, action, record_id, user_id, user_email, old_data)
        values (tg_table_name, tg_op, rec_id, current_user_id, current_user_email, to_jsonb(old));
        return old;

    elsif (tg_op = 'UPDATE') then
        rec_id := coalesce(
            new.article_id::text,
            new.staff_id::text,
            new.pubmat_id::text,
            new.id::text,
            null
        );
        insert into public.audit_logs (table_name, action, record_id, user_id, user_email, old_data, new_data)
        values (tg_table_name, tg_op, rec_id, current_user_id, current_user_email, to_jsonb(old), to_jsonb(new));
        return new;

    elsif (tg_op = 'INSERT') then
        rec_id := coalesce(
            new.article_id::text,
            new.staff_id::text,
            new.pubmat_id::text,
            new.id::text,
            null
        );
        insert into public.audit_logs (table_name, action, record_id, user_id, user_email, new_data)
        values (tg_table_name, tg_op, rec_id, current_user_id, current_user_email, to_jsonb(new));
        return new;
    end if;

    return null;
end;
$$;


-- 4. Attach Triggers to Admin Tables

-- Article table
drop trigger if exists audit_article_trigger on public.article;
create trigger audit_article_trigger
after insert or update or delete on public.article
for each row execute function public.process_audit_log();

-- Releases table
drop trigger if exists audit_releases_trigger on public.releases;
create trigger audit_releases_trigger
after insert or update or delete on public.releases
for each row execute function public.process_audit_log();

-- Staff table
drop trigger if exists audit_staff_trigger on public.staff;
create trigger audit_staff_trigger
after insert or update or delete on public.staff
for each row execute function public.process_audit_log();

-- Pubmat table
drop trigger if exists audit_pubmat_trigger on public.pubmat;
create trigger audit_pubmat_trigger
after insert or update or delete on public.pubmat
for each row execute function public.process_audit_log();

-- Videos table
drop trigger if exists audit_videos_trigger on public.videos;
create trigger audit_videos_trigger
after insert or update or delete on public.videos
for each row execute function public.process_audit_log();

-- Homepage slides table
drop trigger if exists audit_homepage_slides_trigger on public.homepage_slides;
create trigger audit_homepage_slides_trigger
after insert or update or delete on public.homepage_slides
for each row execute function public.process_audit_log();
