import React, { useState, useEffect } from "react"
import { supabase } from "../supabaseClient"
import { compressImage, uploadToR2Storage } from "../utils/imageUtils"
import "./ManagePubmats.css"

export const PUBMAT_CATEGORIES = [
    "ALL",
    "ANNOUNCEMENT",
    "WALANG_PASOK",
    "LOOK",
    "ICYMI",
    "ADVISORY",
    "ALERT",
    "JUST_IN",
    "HAPPENING_NOW",
    "DEVELOPING_STORY",
    "ERRATUM",
    "MAKATA_MONDAYS",
    "TEK_TUESDAY",
    "TALA_THURSDAY",
    "FEATURES_FRIDAY",
    "STREAMING_SATURDAY",
    "SPORTS_SUNDAY",
    "GENERAL"
]

const SQL_HELPER_SNIPPET = `-- 1. If creating pubmat table for the first time:
create table if not exists public.pubmat (
  pubmat_id bigint generated by default as identity not null,
  title text not null,
  category text null default 'GENERAL'::text,
  image_url text null,
  media_id uuid null references public.media (media_id) on update cascade on delete set null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint pubmat_pkey primary key (pubmat_id)
) tablespace pg_default;

-- 2. If table already exists but lacks image_url column, run:
alter table public.pubmat add column if not exists image_url text;`

const ManagePubmats = () => {
    const [pubmats, setPubmats] = useState([])
    const [loading, setLoading] = useState(true)
    const [tableMissing, setTableMissing] = useState(false)
    const [searchQuery, setSearchQuery] = useState("")
    const [categoryFilter, setCategoryFilter] = useState("ALL")

    // Form state for Create / Edit
    const [isFormOpen, setIsFormOpen] = useState(false)
    const [editingPubmatId, setEditingPubmatId] = useState(null)
    const [title, setTitle] = useState("")
    const [category, setCategory] = useState("ANNOUNCEMENT")
    const [isActive, setIsActive] = useState(true)
    const [imageUrl, setImageUrl] = useState("")
    const [existingMediaId, setExistingMediaId] = useState(null)
    const [selectedFile, setSelectedFile] = useState(null)
    const [previewUrl, setPreviewUrl] = useState("")
    const [submitting, setSubmitting] = useState(false)
    const [errorMessage, setErrorMessage] = useState("")

    const fetchPubmats = async () => {
        setLoading(true)
        setTableMissing(false)
        try {
            const { data, error } = await supabase
                .from("pubmat")
                .select("*, media(media_id, media_url)")
                .order("created_at", { ascending: false })

            if (error) {
                // Check if table missing
                if (error.code === "42P01" || error.message?.includes("does not exist") || error.code === "PGRST205") {
                    setTableMissing(true)
                } else {
                    throw error
                }
            } else {
                const formatted = (data || []).map(p => ({
                    ...p,
                    image_url: p.image_url || p.media?.media_url || ""
                }))
                setPubmats(formatted)
            }
        } catch (err) {
            console.error("Error fetching pubmats:", err)
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        fetchPubmats()
    }, [])

    const openCreateForm = () => {
        setEditingPubmatId(null)
        setTitle("")
        setCategory("ANNOUNCEMENT")
        setIsActive(true)
        setImageUrl("")
        setExistingMediaId(null)
        setSelectedFile(null)
        setPreviewUrl("")
        setErrorMessage("")
        setIsFormOpen(true)
    }

    const openEditForm = (pubmat) => {
        setEditingPubmatId(pubmat.pubmat_id)
        setTitle(pubmat.title || "")
        setCategory(pubmat.category || "GENERAL")
        setIsActive(Boolean(pubmat.is_active))
        setImageUrl(pubmat.image_url || "")
        setExistingMediaId(pubmat.media_id || null)
        setSelectedFile(null)
        setPreviewUrl(pubmat.image_url || "")
        setErrorMessage("")
        setIsFormOpen(true)
    }

    const closeForm = () => {
        setIsFormOpen(false)
        setEditingPubmatId(null)
        if (selectedFile && previewUrl && !editingPubmatId) {
            URL.revokeObjectURL(previewUrl)
        }
        setSelectedFile(null)
        setPreviewUrl("")
        setErrorMessage("")
    }

    const handleFileSelect = (e) => {
        const file = e.target.files?.[0]
        if (!file) return
        setSelectedFile(file)
        const localPreview = URL.createObjectURL(file)
        setPreviewUrl(localPreview)
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        if (!title.trim()) {
            setErrorMessage("Please enter a pubmat title.")
            return
        }

        if (!editingPubmatId && !selectedFile) {
            setErrorMessage("Please select an image for this pubmat.")
            return
        }

        setSubmitting(true)
        setErrorMessage("")

        try {
            let finalImageUrl = imageUrl
            let finalMediaId = existingMediaId

            // If a new image file was picked, upload to R2 and save in media table
            if (selectedFile) {
                const compressedBlob = await compressImage(selectedFile)
                const cleanName = selectedFile.name.replace(/\.[^/.]+$/, "") + ".webp"

                const { publicUrl } = await uploadToR2Storage({
                    file: compressedBlob,
                    filename: cleanName,
                    folder: "pubmats",
                    contentType: "image/webp",
                    bucket: "article-photos"
                })

                finalImageUrl = publicUrl

                // Insert into media table so articles can bridge to it
                const { data: mediaRow, error: mediaErr } = await supabase
                    .from("media")
                    .insert([{
                        media_url: publicUrl,
                        media_altText: `PUBMAT: ${title.trim()}`
                    }])
                    .select()
                    .single()

                if (!mediaErr && mediaRow) {
                    finalMediaId = mediaRow.media_id
                }
            }

            const payloadWithImage = {
                title: title.trim(),
                category: category,
                image_url: finalImageUrl,
                media_id: finalMediaId,
                is_active: isActive
            }

            const payloadWithoutImage = {
                title: title.trim(),
                category: category,
                media_id: finalMediaId,
                is_active: isActive
            }

            if (editingPubmatId) {
                // Update: Try with image_url, fallback without if column is missing
                let { error: updateError } = await supabase
                    .from("pubmat")
                    .update(payloadWithImage)
                    .eq("pubmat_id", editingPubmatId)

                if (updateError && (updateError.code === "PGRST204" || updateError.message?.includes("image_url"))) {
                    const fallbackRes = await supabase
                        .from("pubmat")
                        .update(payloadWithoutImage)
                        .eq("pubmat_id", editingPubmatId)
                    updateError = fallbackRes.error
                }

                if (updateError) throw updateError
            } else {
                // Insert: Try with image_url, fallback without if column is missing
                let { error: insertError } = await supabase
                    .from("pubmat")
                    .insert([payloadWithImage])

                if (insertError && (insertError.code === "PGRST204" || insertError.message?.includes("image_url"))) {
                    const fallbackRes = await supabase
                        .from("pubmat")
                        .insert([payloadWithoutImage])
                    insertError = fallbackRes.error
                }

                if (insertError) throw insertError
            }

            closeForm()
            await fetchPubmats()
        } catch (err) {
            console.error("Error saving pubmat:", err)
            setErrorMessage(err.message || "Failed to save pubmat.")
        } finally {
            setSubmitting(false)
        }
    }

    const handleDelete = async (pubmatId, pubmatTitle) => {
        if (!window.confirm(`Are you sure you want to delete the pubmat "${pubmatTitle}"?`)) {
            return
        }

        try {
            const { error } = await supabase
                .from("pubmat")
                .delete()
                .eq("pubmat_id", pubmatId)

            if (error) throw error
            setPubmats(prev => prev.filter(p => p.pubmat_id !== pubmatId))
        } catch (err) {
            console.error("Error deleting pubmat:", err)
            alert("Failed to delete pubmat: " + (err.message || err))
        }
    }

    const handleToggleActive = async (pubmat) => {
        try {
            const nextStatus = !pubmat.is_active
            const { error } = await supabase
                .from("pubmat")
                .update({ is_active: nextStatus })
                .eq("pubmat_id", pubmat.pubmat_id)

            if (error) throw error
            setPubmats(prev => prev.map(p => p.pubmat_id === pubmat.pubmat_id ? { ...p, is_active: nextStatus } : p))
        } catch (err) {
            console.error("Error toggling active status:", err)
            alert("Failed to update status: " + (err.message || err))
        }
    }

    const filteredPubmats = pubmats.filter(pubmat => {
        const matchesCategory = categoryFilter === "ALL" || pubmat.category === categoryFilter
        const matchesSearch = !searchQuery.trim() ||
            (pubmat.title || "").toLowerCase().includes(searchQuery.toLowerCase().trim()) ||
            (pubmat.category || "").toLowerCase().includes(searchQuery.toLowerCase().trim())
        return matchesCategory && matchesSearch
    })

    return (
        <div className="Manage-Pubmats-Container">
            <div className="Manage-Pubmats-Header">
                <div>
                    <h1>Manage Pubmats</h1>
                    <span className="Manage-Pubmats-Count">
                        {pubmats.length} total publication material{pubmats.length === 1 ? "" : "s"}
                    </span>
                </div>
                {!isFormOpen && (
                    <button type="button" className="Pubmat-Btn-New" onClick={openCreateForm}>
                        + New Pubmat
                    </button>
                )}
            </div>

            {tableMissing && (
                <div className="Pubmat-Table-Missing-Banner">
                    <strong>Table "pubmat" Not Found in Supabase</strong>
                    <p>Please run the following SQL query in your Supabase SQL Editor to create the pubmat table:</p>
                    <pre><code>{SQL_HELPER_SNIPPET}</code></pre>
                    <button
                        type="button"
                        className="Pubmat-Btn-Copy-Sql"
                        onClick={async () => {
                            try {
                                await navigator.clipboard.writeText(SQL_HELPER_SNIPPET)
                                alert("SQL copied to clipboard!")
                            } catch (e) {
                                alert("Could not copy automatically. Please copy the text above.")
                            }
                        }}
                    >
                        Copy SQL
                    </button>
                </div>
            )}

            {isFormOpen && (
                <div className="Pubmat-Form-Card">
                    <div className="Pubmat-Form-Header">
                        <h2>{editingPubmatId ? "Edit Pubmat" : "Add New Pubmat"}</h2>
                        <button type="button" className="Pubmat-Form-Close-Btn" onClick={closeForm}>
                            Cancel
                        </button>
                    </div>

                    {errorMessage && (
                        <div className="Pubmat-Form-Error">
                            {errorMessage}
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="Pubmat-Form">
                        <div className="Pubmat-Form-Row">
                            <div className="Pubmat-Form-Field">
                                <label>Pubmat Title</label>
                                <input
                                    type="text"
                                    placeholder="e.g., Walang Pasok Official Graphic Card"
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    required
                                />
                            </div>

                            <div className="Pubmat-Form-Field">
                                <label>Category</label>
                                <select
                                    value={category}
                                    onChange={(e) => setCategory(e.target.value)}
                                >
                                    {PUBMAT_CATEGORIES.filter(c => c !== "ALL").map(cat => (
                                        <option key={cat} value={cat}>{cat}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="Pubmat-Form-Row">
                            <div className="Pubmat-Form-Field">
                                <label>Pubmat Image</label>
                                <label className="Pubmat-File-Upload-Btn">
                                    {selectedFile ? "Change Image File" : "Choose Image File"}
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={handleFileSelect}
                                        style={{ display: "none" }}
                                    />
                                </label>
                            </div>

                            <div className="Pubmat-Form-Field-Checkbox">
                                <label>
                                    <input
                                        type="checkbox"
                                        checked={isActive}
                                        onChange={(e) => setIsActive(e.target.checked)}
                                    />
                                    Active (Available for articles)
                                </label>
                            </div>
                        </div>

                        {previewUrl && (
                            <div className="Pubmat-Form-Preview">
                                <span className="Pubmat-Form-Preview-Label">Preview:</span>
                                <div className="Pubmat-Preview-Box">
                                    <img src={previewUrl} alt="Pubmat preview" />
                                </div>
                            </div>
                        )}

                        <div className="Pubmat-Form-Actions">
                            <button
                                type="button"
                                className="Pubmat-Btn-Secondary"
                                onClick={closeForm}
                                disabled={submitting}
                            >
                                Cancel
                            </button>
                            <button
                                type="submit"
                                className="Pubmat-Btn-Primary"
                                disabled={submitting}
                            >
                                {submitting ? "Saving..." : editingPubmatId ? "Update Pubmat" : "Save Pubmat"}
                            </button>
                        </div>
                    </form>
                </div>
            )}

            {/* Filter and Search Bar */}
            <div className="Pubmat-Toolbar">
                <div className="Pubmat-Search-Wrap">
                    <input
                        type="text"
                        placeholder="Search pubmats by title or category..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="Pubmat-Search-Input"
                    />
                    {searchQuery && (
                        <button
                            type="button"
                            className="Pubmat-Search-Clear"
                            onClick={() => setSearchQuery("")}
                        >
                            Clear
                        </button>
                    )}
                </div>

                <div className="Pubmat-Category-Filters">
                    {PUBMAT_CATEGORIES.map(cat => (
                        <button
                            key={cat}
                            type="button"
                            className={`Pubmat-Category-Pill ${categoryFilter === cat ? "active" : ""}`}
                            onClick={() => setCategoryFilter(cat)}
                        >
                            {cat}
                        </button>
                    ))}
                </div>
            </div>

            {/* Pubmats Grid */}
            {loading ? (
                <div className="Pubmat-Loading">Loading pubmats...</div>
            ) : filteredPubmats.length > 0 ? (
                <div className="Pubmat-Grid">
                    {filteredPubmats.map(pubmat => (
                        <div key={pubmat.pubmat_id} className={`Pubmat-Card ${!pubmat.is_active ? "inactive" : ""}`}>
                            <div className="Pubmat-Card-Image-Wrap">
                                <img src={pubmat.image_url} alt={pubmat.title} />
                                <span className="Pubmat-Card-Category">{pubmat.category || "GENERAL"}</span>
                                {!pubmat.is_active && (
                                    <span className="Pubmat-Card-Status-Inactive">Inactive</span>
                                )}
                            </div>
                            <div className="Pubmat-Card-Body">
                                <h3 className="Pubmat-Card-Title" title={pubmat.title}>
                                    {pubmat.title}
                                </h3>
                                <div className="Pubmat-Card-Actions">
                                    <button
                                        type="button"
                                        className="Pubmat-Card-Btn"
                                        onClick={() => openEditForm(pubmat)}
                                    >
                                        Edit
                                    </button>
                                    <button
                                        type="button"
                                        className="Pubmat-Card-Btn"
                                        onClick={() => handleToggleActive(pubmat)}
                                    >
                                        {pubmat.is_active ? "Deactivate" : "Activate"}
                                    </button>
                                    <button
                                        type="button"
                                        className="Pubmat-Card-Btn Pubmat-Card-Btn-Delete"
                                        onClick={() => handleDelete(pubmat.pubmat_id, pubmat.title)}
                                    >
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="Pubmat-Empty-State">
                    {searchQuery || categoryFilter !== "ALL"
                        ? "No pubmats found matching the selected filters."
                        : "No pubmats have been added yet. Click \"+ New Pubmat\" to add your first template card."}
                </div>
            )}
        </div>
    )
}

export default ManagePubmats
